apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-application
spec:
  project: default
  source:
    repoURL: https://github.com/yassine-elazrak/yelazrak.git
    targetRevision: HEAD
    path: k3d
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
