apiVersion: v1
kind: Service
metadata:
  name: flask-svc
spec:
  type: NodePort
  selector:
    app: flask-pod
  ports:
  - port: 5000
    nodePort: 30002

---

apiVersion: v1
kind: Service
metadata:
  name: node-js-svc
spec:
  type: NodePort
  selector:
    app: node-js-pod
  ports:
  - port: 3000
    nodePort: 30001

    
apiVersion: v1
kind: Service
metadata:
  name: whoami-svc
  namespace: whoami

spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: traefiklabs