server_ip = "192.168.42.110"

server_script = <<-SHELL
    export K3S_KUBECONFIG_MODE="644"
    export INSTALL_K3S_EXEC="--bind-address=#{server_ip} --node-external-ip=#{server_ip} --flannel-iface=eth1"
    curl -sfL https://get.k3s.io | sh - 
    SHELL


Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos7"

  config.vm.define "yelazrakS", primary: true do |server|
    server.vm.network "private_network", ip: server_ip
    server.vm.hostname = "yelazrakS"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = "2"
    end
    server.vm.provision "shell", inline: server_script
  end
end