require 'yaml'

current_dir = File.dirname(File.expand_path(__FILE__))
setting = YAML.load_file("#{current_dir}/config.yaml")

Vagrant.configure("2") do |config|
	config.vm.box = "generic/centos8"

	config.vm.synced_folder setting["shared_host_folder"], setting["shared_guest_folder"], SharedFoldersEnableSymlinksCreate: true

	config.vm.define "zchatouaS" do |w_conf|
		w_conf.vm.hostname = setting["server"]["hostname"]
		w_conf.vm.network  "private_network", ip: setting["server"]["ip"]

		w_conf.vm.provider "virtualbox" do |vb|
			vb.name = setting["server"]["vb_name"]
			vb.memory = setting["server"]["memory"]
			vb.cpus = setting["server"]["cpus"]
			vb.customize  ["modifyvm", :id, "--natdnsproxy1", "off"]
			vb.customize  ["modifyvm", :id, "--natdnshostresolver1", "off"]
		end
		w_conf.vm.provision "shell", path: "./scripts/server.sh", args: [setting["server"]["ip"]]
		
	end

	config.vm.define "zchatouaSW" do |sw_conf|
		sw_conf.vm.hostname = setting["worker"]["hostname"]
		sw_conf.vm.network  "private_network", ip:  setting["worker"]["ip"]

		sw_conf.vm.provider "virtualbox" do |vb|
			vb.name = setting["worker"]["vb_name"]
			vb.memory = setting["worker"]["memory"]
			vb.cpus = setting["worker"]["cpus"]
			vb.customize  ["modifyvm", :id, "--natdnsproxy1", "on"]
			vb.customize  ["modifyvm", :id, "--natdnshostresolver1", "on"]
		end
		sw_conf.vm.provision "shell", path: "./scripts/worker.sh", args: [setting["server"]["ip"], setting["worker"]["ip"]]
	end
end
