require 'yaml'

current_dir = File.dirname(File.expand_path(__FILE__))
setting = YAML.load_file("#{current_dir}/config.yaml")

Vagrant.configure("2") do |config|
	config.vm.box = "generic/ubuntu1804"

	config.vm.synced_folder setting["shared_host_folder"], setting["shared_guest_folder"], SharedFoldersEnableSymlinksCreate: true
	config.vm.network "private_network", ip: setting["server"]["ip"]
	config.vm.network "forwarded_port", guest: 8080, host: 8080
	config.vm.network "forwarded_port", guest: 8181, host: 8181
	config.vm.network "forwarded_port", guest: 8443, host: 8443
	config.vm.network "forwarded_port", guest: 8888, host: 8888
	
	config.vm.define "zchatouaS" do |w_conf|
		w_conf.vm.hostname = setting["server"]["hostname"]

		w_conf.vm.provider "virtualbox" do |vb|
			vb.name = setting["server"]["vb_name"]
			vb.memory = setting["server"]["memory"]
			vb.cpus = setting["server"]["cpus"]
		end		
	end
end
