server_ip = "192.168.42.110"

Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"

  config.vm.define "k3d", primary: true do |server|
    server.vm.network "private_network", ip: server_ip
    server.vm.hostname = "k3d"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = "2"
    end
  end
end