server_ip = "192.168.42.110"

agent_ip = "192.168.42.111"


server_script = <<-SHELL
    export K3S_KUBECONFIG_MODE="644"
    export INSTALL_K3S_EXEC="--bind-address=#{server_ip} --node-external-ip=#{server_ip} --flannel-iface=eth1"
    curl -sfL https://get.k3s.io | sh - 
    # echo "Sleeping for 5 seconds to wait for k3s to start"
    # sleep 5
    # cp /var/lib/rancher/k3s/server/node-token /vagrant
    SHELL
    
agent_script = <<-SHELL
   
    export K3S_TOKEN_FILE=/vagrant/token
    export K3S_URL=https://#{server_ip}:6443
    export INSTALL_K3S_EXEC="--flannel-iface=eth1"
    curl -sfL https://get.k3s.io | sh -
    SHELL

Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"


  config.vm.define "server", primary: true do |server|
    server.vm.network "private_network", ip: server_ip
    # server.vm.synced_folder "./shared", "/vagrant_shared"
    server.vm.hostname = "server"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "1"
    end
    # server.vm.provision "shell", inline: server_script
  end


  config.vm.define "agent1", primary: true do |server|
    server.vm.network "private_network", ip: agent_ip
    # server.vm.synced_folder "./shared", "/vagrant_shared"
    server.vm.hostname = "agent1"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "1"
    end
    # server.vm.provision "shell", inline: server_script
  end


end